### ISSUE TITLE
Dumb question, how to generate the summaries?

### ISSUE THREAD

**Issue by shazz** [pelican-plugins/read-more#8]
Hi,
I added the plugin to the configuration, no issue.
But when displaying the index, Pelican shows all articles completely, no summary or Read more link.

What did I miss?

Thanks!

**Comment by wombelix** [comment]
Hi,

you have to add the `SUMMARY_` and `READ_MORE_` Settings in your pelican config as described in the README: https://github.com/pelican-plugins/read-more?tab=readme-ov-file#settings

An example from my Blog:
https://git.sr.ht/~wombelix/dominik-wombacher-cc/tree/main/item/pelicanconf.py#L96

**Comment by justinmayer** [comment]
@shazz: Hopefully the assistance that @wombelix provided was helpful. If you need further assistance with this issue, please comment here and we can consider re-opening it. Cheers!
